-- ==========================================
-- CAREERBRIDGE - SEQUENCES
-- ==========================================

CREATE SEQUENCE department_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE student_seq
START WITH 101
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE company_seq
START WITH 201
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE role_seq
START WITH 301
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE drive_seq
START WITH 401
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE application_seq
START WITH 501
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE offer_seq
START WITH 601
INCREMENT BY 1
NOCACHE
NOCYCLE;