-- ==========================================
-- CAREERBRIDGE - CREATE TABLES (PostgreSQL)
-- ==========================================

-- ==========================================
-- DEPARTMENTS
-- ==========================================

CREATE TABLE Departments (

    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    department_name VARCHAR(100) NOT NULL UNIQUE,

    hod_name VARCHAR(100) NOT NULL

);

-- ==========================================
-- STUDENTS
-- ==========================================

CREATE TABLE Students (

    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    full_name VARCHAR(100) NOT NULL,

    email VARCHAR(100) NOT NULL UNIQUE,

    phone VARCHAR(15) NOT NULL UNIQUE,

    gender VARCHAR(10)
        CHECK (gender IN ('Male','Female')),

    dob DATE,

    cgpa DECIMAL(3,2)
        CHECK (cgpa BETWEEN 0 AND 10),

    graduation_year INTEGER,

    department_id INTEGER NOT NULL,

    CONSTRAINT fk_student_department
        FOREIGN KEY (department_id)
        REFERENCES Departments(department_id)

);

-- ==========================================
-- COMPANIES
-- ==========================================

CREATE TABLE Companies (

    company_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_name VARCHAR(100) NOT NULL UNIQUE,

    location VARCHAR(100),

    website VARCHAR(150),

    hr_email VARCHAR(100)

);

-- ==========================================
-- JOB ROLES
-- ==========================================

CREATE TABLE JobRoles (

    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id INTEGER NOT NULL,

    role_name VARCHAR(100) NOT NULL,

    salary_lpa DECIMAL(4,2),

    minimum_cgpa DECIMAL(3,2),

    vacancies INTEGER,

    CONSTRAINT fk_role_company
        FOREIGN KEY (company_id)
        REFERENCES Companies(company_id)

);

-- ==========================================
-- PLACEMENT DRIVES
-- ==========================================

CREATE TABLE PlacementDrives (

    drive_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_id INTEGER NOT NULL,

    drive_date DATE,

    venue VARCHAR(100),

    registration_deadline DATE,

    status VARCHAR(20)
        CHECK (status IN ('Upcoming','Ongoing','Completed')),

    CONSTRAINT fk_drive_company
        FOREIGN KEY (company_id)
        REFERENCES Companies(company_id)

);

-- ==========================================
-- APPLICATIONS
-- ==========================================

CREATE TABLE Applications (

    application_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    student_id INTEGER NOT NULL,

    role_id INTEGER NOT NULL,

    application_date DATE,

    status VARCHAR(20)
        CHECK (status IN ('Applied','Shortlisted','Interview','Selected','Rejected')),

    CONSTRAINT fk_application_student
        FOREIGN KEY (student_id)
        REFERENCES Students(student_id),

    CONSTRAINT fk_application_role
        FOREIGN KEY (role_id)
        REFERENCES JobRoles(role_id)

);

-- ==========================================
-- OFFERS
-- ==========================================

CREATE TABLE Offers (

    offer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    application_id INTEGER UNIQUE,

    package_lpa DECIMAL(4,2),

    joining_date DATE,

    offer_status VARCHAR(20)
        CHECK (offer_status IN ('Accepted','Pending','Rejected')),

    CONSTRAINT fk_offer_application
        FOREIGN KEY (application_id)
        REFERENCES Applications(application_id)

);