-- ==========================================
-- CAREERBRIDGE - TRIGGERS (PostgreSQL)
-- ==========================================

--------------------------------------------------
-- 1. Validate Student CGPA
--------------------------------------------------

CREATE OR REPLACE FUNCTION validate_cgpa()
RETURNS TRIGGER AS
$$
BEGIN

    IF NEW.cgpa < 0 OR NEW.cgpa > 10 THEN
        RAISE EXCEPTION 'CGPA must be between 0 and 10.';
    END IF;

    RETURN NEW;

END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validate_cgpa
BEFORE INSERT OR UPDATE OF cgpa
ON Students
FOR EACH ROW
EXECUTE FUNCTION validate_cgpa();

--------------------------------------------------
-- 2. Auto Set Application Date
--------------------------------------------------

CREATE OR REPLACE FUNCTION application_date_trigger()
RETURNS TRIGGER AS
$$
BEGIN

    IF NEW.application_date IS NULL THEN
        NEW.application_date := CURRENT_DATE;
    END IF;

    RETURN NEW;

END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_application_date
BEFORE INSERT
ON Applications
FOR EACH ROW
EXECUTE FUNCTION application_date_trigger();

--------------------------------------------------
-- 3. Validate Joining Date
--------------------------------------------------

CREATE OR REPLACE FUNCTION validate_joining_date()
RETURNS TRIGGER AS
$$
DECLARE
    v_application_date DATE;
BEGIN

    SELECT application_date
    INTO v_application_date
    FROM Applications
    WHERE application_id = NEW.application_id;

    IF NEW.joining_date < v_application_date THEN
        RAISE EXCEPTION
        'Joining date cannot be before application date.';
    END IF;

    RETURN NEW;

END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validate_joining_date
BEFORE INSERT OR UPDATE
ON Offers
FOR EACH ROW
EXECUTE FUNCTION validate_joining_date();

--------------------------------------------------
-- 4. Student CGPA Log Table
--------------------------------------------------

CREATE TABLE Student_CGPA_Log
(

    log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    student_id INTEGER,

    old_cgpa DECIMAL(3,2),

    new_cgpa DECIMAL(3,2),

    updated_on DATE

);

--------------------------------------------------
-- 5. Log Student CGPA Updates
--------------------------------------------------

CREATE OR REPLACE FUNCTION cgpa_log_trigger()
RETURNS TRIGGER AS
$$
BEGIN

    INSERT INTO Student_CGPA_Log
    (
        student_id,
        old_cgpa,
        new_cgpa,
        updated_on
    )
    VALUES
    (
        OLD.student_id,
        OLD.cgpa,
        NEW.cgpa,
        CURRENT_DATE
    );

    RETURN NEW;

END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_cgpa_log
AFTER UPDATE OF cgpa
ON Students
FOR EACH ROW
EXECUTE FUNCTION cgpa_log_trigger();